----- Query 1
SELECT 
COUNT(FACT.SESS_ID) AS NumberOfSession
,COVER_D.COVER_DESCRIPTION AS TypeOfCover
,MCAL_D.MONTH_NAME AS MonthName
FROM
DWH_SESS_TEMPREQ_DY_F FACT
,DWH_MCAL_DAY_D MCAL_D
,DWH_TYPE_OF_COVER COVER_D
WHERE 
FACT.TYPE_OF_COVER_WID = COVER_D.ROW_WID
AND FACT.SESSION_DT_WID = MCAL_D.ROW_WID
GROUP BY 
COVER_D.COVER_DESCRIPTION
,MCAL_D.MONTH_NAME
ORDER BY
1;

--------Query 2
SELECT 
COUNT(FACT.REQ_ID) AS NumberOfSession
,COUNCIL_D.LOCALCOUNCIL_NAME AS CouncilName
,MCAL_D.WEEKNAME as WEEKNAME
FROM
DWH_SESS_TEMPREQ_DY_F FACT
,DWH_MCAL_DAY_D MCAL_D
,DWH_COUNCIL_D COUNCIL_D
WHERE
FACT.CNCIL_WID = COUNCIL_D.ROW_WID
AND FACT.SESSION_DT_WID = MCAL_D.ROW_WID
GROUP BY 
COUNCIL_D.LOCALCOUNCIL_NAME
,MCAL_D.WEEKNAME
ORDER BY COUNCIL_D.LOCALCOUNCIL_NAME;

---------- Query 3

SELECT 
COUNT(FACT.REQ_ID) AS NumberOfSession
,COUNCIL_D.LOCALCOUNCIL_NAME AS CouncilName
,MCAL_D.MONTH_NAME AS MonthName
,MCAL_D.YEAR AS YEAR
FROM
DWH_SESS_TEMPREQ_DY_F FACT
,DWH_MCAL_DAY_D MCAL_D
,DWH_COUNCIL_D COUNCIL_D
,DWH_TEMP_INFO_D TEMP_INFO_D
WHERE
FACT.CNCIL_WID = COUNCIL_D.ROW_WID
AND FACT.SESSION_DT_WID = MCAL_D.ROW_WID
AND TEMP_INFO_D.ROW_WID = FACT.TEMP_INF_WID
AND  TEMP_INFO_D.TEMP_ID = 0
GROUP BY 
COUNCIL_D.LOCALCOUNCIL_NAME
,MCAL_D.MONTH_NAME
,MCAL_D.YEAR
ORDER BY MCAL_D.MONTH_NAME;

------------ Query 4
SELECT 
COUNT(FACT.REQ_ID) AS NumberOfSession
,COUNCIL_D.LOCALCOUNCIL_NAME AS CouncilName
,MCAL_D.WEEKNAME AS WEEKNAME
FROM
DWH_SESS_TEMPREQ_DY_F FACT
,DWH_MCAL_DAY_D MCAL_D
,DWH_COUNCIL_D COUNCIL_D
,DWH_TEMP_INFO_D TEMP_INFO_D
WHERE
FACT.CNCIL_WID = COUNCIL_D.ROW_WID
AND FACT.SESSION_DT_WID = MCAL_D.ROW_WID
AND TEMP_INFO_D.ROW_WID = FACT.TEMP_INF_WID
AND  TEMP_INFO_D.TEMP_ID != 0
GROUP BY 
COUNCIL_D.LOCALCOUNCIL_NAME
,MCAL_D.WEEKNAME
ORDER BY MCAL_D.WEEKNAME;

-------------Query 5

SELECT 
COUNT(FACT.REQ_ID) AS NumberOfSession
,MCAL_D.MONTH_NAME AS MonthName
,MCAL_D.YEAR AS YEAR
,FACT.STATUS AS REASON
FROM
DWH_SESS_TEMPREQ_DY_F FACT
,DWH_MCAL_DAY_D MCAL_D
WHERE
 FACT.SESSION_DT_WID = MCAL_D.ROW_WID
AND FACT.STATUS IN ('Temp Cancelled','Branch Cancelled')
GROUP BY 
MCAL_D.MONTH_NAME
,FACT.STATUS
,MCAL_D.YEAR
ORDER BY MCAL_D.MONTH_NAME
;